// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc3946.UltimateAscent;
    
import edu.wpi.first.wpilibj.Jaguar;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainfrontLeft;
    public static SpeedController driveTrainrearLeft;
    public static SpeedController driveTrainfrontRight;
    public static SpeedController driveTrainrearRight;
    public static RobotDrive driveTrainrobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainfrontLeft = new Jaguar(1, 1);
	LiveWindow.addActuator("DriveTrain", "frontLeft", (Jaguar) driveTrainfrontLeft);
        
        driveTrainrearLeft = new Jaguar(1, 2);
	LiveWindow.addActuator("DriveTrain", "rearLeft", (Jaguar) driveTrainrearLeft);
        
        driveTrainfrontRight = new Jaguar(1, 3);
	LiveWindow.addActuator("DriveTrain", "frontRight", (Jaguar) driveTrainfrontRight);
        
        driveTrainrearRight = new Jaguar(1, 4);
	LiveWindow.addActuator("DriveTrain", "rearRight", (Jaguar) driveTrainrearRight);
        
        driveTrainrobotDrive = new RobotDrive(driveTrainfrontLeft, driveTrainrearLeft,
              driveTrainfrontRight, driveTrainrearRight);
	
        driveTrainrobotDrive.setSafetyEnabled(true);
        driveTrainrobotDrive.setExpiration(0.1);
        driveTrainrobotDrive.setSensitivity(0.5);
        driveTrainrobotDrive.setMaxOutput(1.0);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
